# Site settings
title: 努力学习中
author :
  name : fangler
  email : ifangler@163.com

description: > # this means to ignore newlines until "baseurl:"
             fangler的个人博客，记录android开发的一些事
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fangler.github.io" # the base hostname & protocol for your site

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://fangler.github.io


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'

# Social account
# twitter:  username
# weibo:    ID
# github:   username
# codepen:  username
# dribbble: username


# Comment
comments : duoshuo


# Google Analytics
# google_analytics: tracking_ID


# Build settings
#
#host : 192.168.170.128

